- name: set zone to /etc/sysconfig/clock
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^ZONE=\"UTC\"'
    replace='ZONE="{{zone}}"'
- name: set localtime
  file: >
    src={{zoneinfo_path}}
    dest=/etc/localtime
    state=link
    force=yes
